const constants = {
    ALREADY_EXISTS:'Account with this email already exists',
    SERVER_ERROR:"Something went wrong, please try again.",
    USR_CRT_SUC:"User created successfully.",
    USR_CRT_ERR:"Error creating account.",
    INVALID_CREDENTIALS:"Invalid credentials please check you username and password.",
    USR_SIGNIN_SUC:"Logged in successfully",
    USR_SIGNIN_ERR:"Error Loogging in.",
    USR_NOT_FOUND:"User not found",
    TOKEN_MISSING:"Token missing from request",
    USR_LNG_ER:"User not logged in",
    USRS_DT_SC: "Users data retrieved successfully",
    USRS_DT_FL: "Error retrieving users data",
    USR_DT_SC: "User data retrieved successfully",
    USR_DT_FL: "Error retrieving user data",
    USR_LG_OUT_SC:"User logged out successfully",
    USR_LG_OUT_FL:"Error logging out User",
    USR_UPD_SC: 'User updated successfully',
    USR_DEL_SC: "User deleted successfully",
    USR_DEL_ERR: "Error deleting user",
    PRD_UP_SC: 'Product uploaded successfully',
    PRD_UP_FL:'An error occurred while uploading the product',
    PRD_UPD_SC: 'Product updated successfully',
    PRD_UPD_FL:'An error occurred while updating the product',
    PRD_GET_FL:'An error occurred while fetching the products',
    PRD_GET_SC:"All products retrieved successfully",
    PRD_DEL_FL:'An error occurred while fetching the products',
    PRD_DEL_SC:"All products retrieved successfully",
    PRD_NT_FD:'Product not found'
};

module.exports = constants;